function [cgenes] = importGenesfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 03-Feb-2010 18:15:17

% Import the file
fprintf(2, 'importGenesFile(): reading %s ', fileToRead1); 
rawData1 = importdata(fileToRead1);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[unused,name] = fileparts(fileToRead1); % ok
newData1.(genvarname(name)) = rawData1;

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);

for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
cgenes = newData1.(genvarname(vars{1})); 
fprintf(2, ' ... read %d genes\n', length(cgenes));  
